export const START_TIMER = 'timer/START_TIMER'
export const STOP_TIMER = 'timer/STOP_TIMER'
export const RESET_TIMER = 'timer/RESET_TIMER'
export const SET_SESSION_LENGTH = 'timer/SET_SESSION_LENGTH'
export const SET_TASK = 'task/SET_TASK'
export const SET_ALERT = 'task/SET_ALERT'
export const INCREMENT_INTERRUPTIONS = 'efficiency/INCREMENT_INTERRUPTIONS'
export const TOGGLE_MODE = 'timer/TOGGLE_MODE'