export const TOGGLE_TIMER = 'timer/TOGGLE_TIMER'
export const START_TIMER = 'timer/START_TIMER'
export const STOP_TIMER = 'timer/STOP_TIMER'
export const RESET_TIMER = 'timer/RESET_TIMER'
export const SET_TASK = 'task/SET_TASK'
export const INCREMENT_INTERRUPTIONS = 'efficiency/INCREMENT_INTERRUPTIONS'